### ISSUE TITLE
Related tags and "active" class

### ISSUE THREAD

**Issue by biowebfr** [hschottm/tags#88]
Hi,

I love your extension. It does an awsome job, I use it for many years (since contao 3)!

I have a question regarding the "active" class.

Is it possible to add the "active" class to the related tags selected ?

![image](https://user-images.githubusercontent.com/46192868/202850428-5b90cd65-fbff-4731-b24a-50b5120875b9.png)

Thank you for your response.

**Comment by hschottm** [comment]
Hi Renaud,

sure that should be possible, I will have a look at it.

Cheers,

Helmut


Am Sa., 19. Nov. 2022 um 13:18 Uhr schrieb Renaud Kaczmarek <
***@***.***>:

**Comment by biowebfr** [comment]
Great ! Maybe the related tag could have a class .related too. :)

**Comment by hschottm** [comment]
I added a related CSS class for all chosen related tags in the "All tags" and the "Top 10 tags" tag clouds. I also added an active CSS class for the active tag into the "Top 10 tags" tag cloud.
I don't add an active to the selected related tags because technically they are not active. There is only one active tag possible. But you can use the new related CSS class to create your 'active' styling for the selected related tags.

**Comment by biowebfr** [comment]
Brilliant!
